--光晕『唐伞惊吓闪光』
function c26091.initial_effect(c)
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetCategory(CATEGORY_DAMAGE)
	e1:SetCountLimit(1,26091+EFFECT_COUNT_CODE_DUEL)
	e1:SetCost(c26091.cost)
	e1:SetTarget(c26091.target)
	e1:SetOperation(c26091.activate)
	c:RegisterEffect(e1)
	Duel.AddCustomActivityCounter(26091,ACTIVITY_SUMMON,c26091.counterfilter)
	Duel.AddCustomActivityCounter(26091,ACTIVITY_SPSUMMON,c26091.counterfilter)
end
function c26091.counterfilter(c)
	return c:IsSetCard(0x229)
end
function c26091.cffilter(c)
	return c:IsSetCard(0x229) and not c:IsPublic()
end
function c26091.cost(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsExistingMatchingCard(c26091.cffilter,tp,LOCATION_HAND,0,1,e:GetHandler()) 
		and Duel.GetCustomActivityCount(26091,tp,ACTIVITY_SUMMON)==0
		and Duel.GetCustomActivityCount(26091,tp,ACTIVITY_SPSUMMON)==0 end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_CONFIRM)
	local g=Duel.SelectMatchingCard(tp,c26091.cffilter,tp,LOCATION_HAND,0,1,1,e:GetHandler())
	Duel.ConfirmCards(1-tp,g)
	Duel.ShuffleHand(tp)
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET+EFFECT_FLAG_OATH)
	e1:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
	e1:SetReset(RESET_PHASE+PHASE_END)
	e1:SetTargetRange(1,0)
	e1:SetTarget(c26091.sumlimit)
	Duel.RegisterEffect(e1,tp)
	local e5=e1:Clone()
	e5:SetCode(EFFECT_CANNOT_SUMMON)
	Duel.RegisterEffect(e5,tp)
end
function c26091.sumlimit(e,c,sump,sumtype,sumpos,targetp,se)
	return not c:IsSetCard(0x229)
end
function c26091.target(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetCurrentPhase()==PHASE_DRAW or Duel.GetCurrentPhase()==PHASE_MAIN1 end
	Duel.SetOperationInfo(0,CATEGORY_DAMAGE,nil,0,1-tp,200)
end
function c26091.activate(e,tp,eg,ep,ev,re,r,rp)
	Duel.Damage(1-tp,200,REASON_EFFECT)
	local e1=Effect.CreateEffect(e:GetHandler())
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetCode(EFFECT_CANNOT_EP)
	e1:SetTargetRange(1,0)
	e1:SetReset(RESET_PHASE+PHASE_END+RESET_OPPO_TURN)
	Duel.RegisterEffect(e1,tp)
	local e2=e1:Clone()
	e2:SetCode(EFFECT_SKIP_SP)
	Duel.RegisterEffect(e2,tp)
	local e3=e1:Clone()
	e3:SetCode(EFFECT_SKIP_BP)
	Duel.RegisterEffect(e3,tp)
	local e5=e1:Clone()
	e5:SetCode(EFFECT_SKIP_DP)
	e5:SetTargetRange(0,1)
	Duel.RegisterEffect(e5,tp)
	local e6=e5:Clone()
	e6:SetCode(EFFECT_SKIP_SP)
	Duel.RegisterEffect(e6,tp)
	local e7=e5:Clone()
	e7:SetCode(EFFECT_SKIP_M1)
	Duel.RegisterEffect(e7,tp)
	local e8=e5:Clone()
	e8:SetCode(EFFECT_CANNOT_BP)
	Duel.RegisterEffect(e8,tp)
	Duel.SkipPhase(tp,PHASE_MAIN1,RESET_PHASE+PHASE_END,1)
	if Duel.GetCurrentPhase()==PHASE_DRAW then
		Duel.SkipPhase(tp,PHASE_DRAW,RESET_PHASE+PHASE_END,1)
	end
end
